/* generated by pull.js */
const manifest = {
    "editorOnly": true,
    "noTranslations": true,
    "name": "Copy reporter values",
    "description": "Adds the option to copy values displayed by variable monitors (from the right click context menu) and block reporter balloons.",
    "credits": [
      {
        "name": "TheKodeToad",
        "link": "#"
      },
      {
        "name": "Scratch Addons"
      }
    ],
    "userscripts": [
      {
        "url": "userscript.js"
      }
    ],
    "tags": [
      "OrangeMod"
    ],
    "enabledByDefault": false
  };
  export default manifest;
  